version: '3'
services:
    mysql:
        image: mysql:5
        ports:
            - 3306:3306
        volumes:
            - rds-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: bot
            MYSQL_USER: bot
            MYSQL_PASSWORD: bot
    bot:
        build: .
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            DEBUG: 1
            ENVIRONMENT: 'dev'
            SECRETS_FILE: "/app/dev.secrets.json"
        volumes:
            - .:/app

volumes:
    rds-data: ~
