version: 2
jobs:
    build:
        docker:
            -   image: circleci/<language>:<version TAG>
        steps:
            - checkout
            -   run: <command>
    test:
        docker:
            -   image: circleci/<language>:<version TAG>
        steps:
            - checkout
            -   run: <command>
    lint:
        docker:
            -   image: circleci/nodejs:10
        steps:
            - checkout
            -   run: npm run lint

workflows:
    version: 2
    lint:
        jobs:
            - lint
    build_and_deploy:
        jobs:
            - build
            -   deploy:
                    filters:
                        branches:
                            only:
                                - master
